#!/usr/bin/env python3
"""scripts/arrival_checklist.py — the arrival / first-article checklist, GENERATED from a yaml (SKILL.md §10.1; references/release-and-cut.md §10).

  scripts/arrival_checklist.py              # write <arrival_checklist.out> from <arrival_checklist.yaml> (project.yaml keys; defaults
                                            #   20-design/arrival_checklist.yaml -> 60-orders/ARRIVAL_CHECKLIST_rev0.md)
  scripts/arrival_checklist.py --check      # exit 1 when the markdown is stale or the yaml breaks a rule (nothing written)
  scripts/arrival_checklist.py --selftest   # temp dir only

The yaml: `version`, `title`, `sections: [{key, title, note?, columns, rows: [{id, item, …, status, evidence}]}]`. Rules (`--check` and every
plain run enforce them): every row has `id`, `item`, `status`, `evidence`; `status` is `TODO`, `N/A`, `DONE <YYYY-MM-DD>` or `APPLIED <YYYY-MM-DD>…`
(a DONE / APPLIED row needs a non-empty `evidence` cell); row ids are unique; every section lists its `columns` and every row's keys are a subset
of them. Closing a row = editing the yaml, regenerating, committing — the markdown is never hand-edited (rule 5). Exit 2 = input missing.
"""
import argparse, os, re, sys, tempfile

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
from project import Project  # noqa: E402

STATUS = re.compile(r"^(TODO|N/A|(DONE|APPLIED) \d{4}-\d{2}-\d{2}.*)$")


def validate(y):
    """-> problem list (empty = the yaml obeys the rules)."""
    bad, seen = [], set()
    for s in y.get("sections") or []:
        cols = s.get("columns") or []
        for need in ("id", "item", "status", "evidence"):
            if need not in cols:
                bad.append(f"section {s.get('key')}: columns lack `{need}`")
        for r in s.get("rows") or []:
            rid = str(r.get("id", ""))
            if not rid or not r.get("item"):
                bad.append(f"section {s.get('key')}: a row without id / item ({r})"); continue
            if rid in seen:
                bad.append(f"duplicate row id {rid}")
            seen.add(rid)
            st = str(r.get("status", ""))
            if not STATUS.match(st):
                bad.append(f"{rid}: status `{st}` is not TODO | N/A | DONE <date> | APPLIED <date>")
            elif st.startswith(("DONE", "APPLIED")) and not str(r.get("evidence", "")).strip():
                bad.append(f"{rid}: {st.split()[0]} without evidence")
            extra = set(r) - set(cols)
            if extra:
                bad.append(f"{rid}: keys not in the section's columns: {sorted(extra)}")
    if not y.get("sections"):
        bad.append("no sections")
    return bad


def render(y, yaml_rel, tool_rel="scripts/arrival_checklist.py"):
    L = [f"# {y.get('title', 'ARRIVAL_CHECKLIST')}", "",
         f"GENERATED by `{tool_rel}` from `{yaml_rel}` ({y.get('version', '?')}) — edit the yaml, regenerate (rule 5). Status cell = `TODO` | `DONE <date>` | "
         "`N/A` | `APPLIED <date>` (owner veto window open); evidence = the file, photo or commit that closes the row. Sections in the order of the day: "
         "what is checked before the shipment is approved, the bench checks in gate order (the `opens` column says what each row releases), the "
         "software gates with their closing commit, the first article, then the owner's open calls with the measurement that resolves each.", ""]
    tot = {}
    for s in y["sections"]:
        rows = s.get("rows") or []
        done = sum(1 for r in rows if str(r.get("status", "")).startswith(("DONE", "APPLIED")))
        na = sum(1 for r in rows if str(r.get("status", "")) == "N/A")
        tot[s["key"]] = (len(rows), done, na)
        L += [f"## {s['key']}. {s['title']}", ""]
        if s.get("note"):
            L += [f"> {s['note']}", ""]
        cols = s["columns"]
        L += ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
        L += ["| " + " | ".join(str(r.get(c, "")).replace("|", "\\|") for c in cols) + " |" for r in rows]
        L.append("")
    L += ["## Row counts", "", "| section | rows | DONE / APPLIED | N/A | open |", "|---|---|---|---|---|"]
    L += [f"| {k} | {n} | {d} | {na} | {n - d - na} |" for k, (n, d, na) in tot.items()]
    a = [sum(v[i] for v in tot.values()) for i in range(3)]
    L.append(f"| **all** | {a[0]} | {a[1]} | {a[2]} | {a[0] - a[1] - a[2]} |")
    return "\n".join(L) + "\n"


def build(P):
    import yaml
    src = P.get("arrival_checklist.yaml", "20-design/arrival_checklist.yaml"); out = P.get("arrival_checklist.out", f"60-orders/ARRIVAL_CHECKLIST_{P.rev()}.md")
    sp = os.path.join(P.root, src)
    if not os.path.exists(sp):
        print(f"arrival_checklist: MISSING {src}"); return None, None, None
    y = yaml.safe_load(open(sp, encoding="utf-8")) or {}
    bad = validate(y)
    return render(y, src) if not bad else None, os.path.join(P.root, out), bad


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0]); ap.add_argument("--check", action="store_true"); ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args(argv[1:])
    if a.selftest:
        return selftest()
    P = Project.find()
    md, out, bad = build(P)
    if out is None:
        return 2
    for b in bad:
        print("arrival_checklist:", b)
    if bad:
        return 1
    if a.check:
        if not os.path.exists(out) or open(out, encoding="utf-8").read() != md:
            print(f"arrival_checklist --check: {os.path.relpath(out, P.root)} stale or missing -> run scripts/arrival_checklist.py"); return 1
        print("arrival_checklist --check: up to date"); return 0
    os.makedirs(os.path.dirname(out), exist_ok=True); open(out, "w", encoding="utf-8").write(md); print(f"{os.path.relpath(out, P.root)} written"); return 0


def selftest():
    import yaml
    d = tempfile.mkdtemp(prefix="hwfs_arrival_"); os.makedirs(f"{d}/20-design")
    open(f"{d}/project.yaml", "w").write("project: {name: t}\n")
    good = {"version": "1-2026-01-01", "title": "T", "sections": [
        {"key": "A", "title": "Before shipment", "columns": ["id", "item", "how", "fail", "opens", "status", "evidence"],
         "rows": [{"id": "A-1", "item": "polarity vs silk", "how": "zoom", "fail": "re-place", "opens": "B-1", "status": "TODO", "evidence": ""}]},
        {"key": "E", "title": "Owner decisions", "columns": ["id", "item", "trigger", "status", "evidence"],
         "rows": [{"id": "E-1", "item": "fit knob after the bracket print", "trigger": "first print", "status": "DONE 2026-01-02", "evidence": "D-09"}]}]}
    yaml.safe_dump(good, open(f"{d}/20-design/arrival_checklist.yaml", "w"))
    assert validate(good) == [], validate(good)
    import contextlib, io
    os.chdir(d); assert main(["x"]) == 0
    md = open(f"{d}/60-orders/ARRIVAL_CHECKLIST_rev0.md").read()
    assert "| A-1 |" in md and "| E | 1 | 1 | 0 | 0 |" in md and "| **all** | 2 | 1 | 0 | 1 |" in md and "GENERATED" in md, md
    assert main(["x", "--check"]) == 0
    open(f"{d}/60-orders/ARRIVAL_CHECKLIST_rev0.md", "a").write("hand edit\n"); assert main(["x", "--check"]) == 1, "a hand-edited markdown is stale"
    bad = dict(good); bad["sections"] = [dict(good["sections"][0], rows=[dict(good["sections"][0]["rows"][0], status="done"), dict(good["sections"][0]["rows"][0], status="DONE 2026-01-03", evidence="", extra=1)])]
    b = validate(bad); assert any("not TODO" in x for x in b) and any("without evidence" in x for x in b) and any("duplicate" in x for x in b) and any("keys not in" in x for x in b), b
    yaml.safe_dump(bad, open(f"{d}/20-design/arrival_checklist.yaml", "w"))
    with contextlib.redirect_stdout(io.StringIO()):
        assert main(["x", "--check"]) == 1 and main(["x"]) == 1, "rule breaks fail both modes"
        os.remove(f"{d}/20-design/arrival_checklist.yaml"); assert main(["x", "--check"]) == 2, "missing yaml = 2"
    print("selftest OK (render, counts, --check stale, status grammar, DONE needs evidence, duplicate ids, foreign keys, missing yaml = 2)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
