#!/usr/bin/env python3
"""scripts/assembly_guide.py — an ILLUSTRATED assembly guide beside the text SOP: one clean render per page, three lines of text, what you hold /
use / check (references/release-and-cut.md §8). Generated-only: authored SHORT yaml + generated step text + keyed renders.

  scripts/assembly_guide.py            build <assembly_guide.out_dir>/<doc_name> + guide/*.png + guide/guide.json (renders only when their key moved)
  scripts/assembly_guide.py --check    exit 1 when the .md or any render key is stale against its inputs (never renders, never writes)
  scripts/assembly_guide.py --selftest

project.yaml `assembly_guide:` (references/project-yaml.md): yaml (authored pages), steps_md (optional generated step source with
`### Step N - title (T s)` headings + a paragraph: the first two sentences become the caption), scad (the geometry of record; its md5 keys every
render), render_cmd (shell template: {OUT} {CAMERA} {DEFS} {SIZE}; {DEFS} expands to `-Dk=v` pairs), out_dir ({REV} = project.revision, {MD5_8} = board md5, {CASE_VERSION}),
doc_name, size. `render_cmd` is a str.format template: any other literal brace is written `{{ }}`; yaml booleans in defs are lowered
to `true` / `false`; the scad key covers the ONE file named (a flattened scad, or accept that `include <…>` edits do not move the key). Authored yaml: doc{doc_id,title,revision,date,companions,how_to_read}, parts[], tools[], defaults{defs}, pages[] (position
before|after, heading, defs, camera, lines[], parts[], tools[], check), step_defaults{camera, defs}, steps{n: {camera, parts, tools, check,
title?, lines?}} — title/lines only when there is no steps_md. Numbers stay in the SOP / manufacturing spec (one source); this guide points at them.
Renders are keyed on (scad md5, defs, camera, size): a geometry bump re-renders every page, a text edit renders nothing.
"""
import argparse, hashlib, json, os, re, shlex, subprocess, sys, tempfile

import yaml

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
from project import Project  # noqa: E402


def md5(p, n=8):
    return hashlib.md5(open(p, "rb").read()).hexdigest()[:n]


def parse_steps(text):
    """'### Step N - title (T s)' + paragraph -> {n: (title, secs, caption)}; caption = the first two sentences, <= 360 chars."""
    steps = {}
    for m in re.finditer(r"^### Step (\d+) - (.+?)(?: \((\d+) s\))?\n\n(.*?)(?:\n\n|\Z)", text, re.M | re.S):
        n, title, secs, para = int(m.group(1)), m.group(2).strip(), m.group(3), m.group(4).strip()
        cap = " ".join(re.split(r"(?<=[.!?])\s+(?=[A-Z0-9])", para)[:2]).strip()
        if len(cap) > 360:
            cap = cap[:357].rsplit(" ", 1)[0] + "…"
        steps[n] = (title, int(secs) if secs else None, cap)
    return steps


def pages(cfg, steps):
    """[(stem, defs, camera, heading, lines, parts, tools, check)] — fixed pages before, steps in order, fixed pages after."""
    base = dict(cfg.get("defaults", {}).get("defs", {}))
    fixed = lambda pos: [(f"page_{p['id']}", {**base, **p.get("defs", {})}, p["camera"], p["heading"], p.get("lines", []), p.get("parts", []), p.get("tools", []), p.get("check", ""))
                         for p in cfg.get("pages", []) if p.get("position", "after") == pos]
    sd = cfg.get("step_defaults", {}); authored = {int(k): v for k, v in (cfg.get("steps") or {}).items()}
    out = fixed("before")
    for n in sorted(set(steps) | set(authored)):
        s = authored.get(n, {})
        title, secs, cap = steps.get(n, (s.get("title", f"step {n}"), s.get("secs"), " ".join(s.get("lines", []))))
        head = f"Step {n} — {title}" + (f" ({secs} s)" if secs else "")
        out.append((f"step_{n:02d}", {**base, **sd.get("defs", {}), **s.get("defs", {}), "step": n}, s.get("camera", sd.get("camera", "")), head, [cap] if cap else [],
                    s.get("parts", []), s.get("tools", []), s.get("check", "")))
    return out + fixed("after")


def build_md(cfg, pgs, k, doc_name, size):
    d = cfg["doc"]
    L = [f"# {doc_name} — {d['title']}", "",
         "GENERATED by `scripts/assembly_guide.py` from the authored guide yaml, the generated step text and the case geometry of record — do not hand-edit.", "",
         "| | |", "|---|---|", f"| Document | {d['doc_id']} — {d['title']} |", f"| Revision / date | **{d['revision']}**, {d['date']} |",
         f"| Applies to | board `{k.get('board', 'MISSING')}`, case `{k.get('case', 'MISSING')}` |", f"| Companion documents | {d.get('companions', '—')} |",
         f"| Pictures | {len(pgs)} renders of the geometry of record (`guide/*.png`, {size} px); keys in `guide/guide.json` |", "",
         f"**How to read this guide.** {d.get('how_to_read', 'One picture per step; the words with the numbers are in the companion documents.')}", "",
         "## 0. What arrives per unit", "", *[f"- {p}" for p in cfg.get("parts", [])], "", "**Tools**", "", *[f"- {t}" for t in cfg.get("tools", [])], ""]
    for stem, _defs, _cam, head, lines, parts, tools, check in pgs:
        L += [f"## {head}", "", f"![{head}](guide/{stem}.png)", ""] + list(lines) + ([""] if lines else [])
        if parts or tools or check:
            L += ["| You hold | You use | You check |", "|---|---|---|", f"| {'<br>'.join(parts) or '—'} | {'<br>'.join(tools) or '—'} | {check or '—'} |", ""]
    L += ["## Where the words are", "", *[f"- {w}" for w in cfg.get("where_the_words_are", [])], "",
          f"Sources: guide yaml `{k['yaml']}`, steps `{k.get('steps', '—')}`, geometry `{k['scad']}`."]
    return "\n".join(L) + "\n"


def run(P, check=False):
    A = P.get("assembly_guide") or (print("project.yaml has no assembly_guide: block (references/project-yaml.md)"), sys.exit(2))
    yaml_p, scad = os.path.join(P.root, A["yaml"]), os.path.join(P.root, A["scad"])
    cfg = yaml.safe_load(open(yaml_p)); size = str(A.get("size", "1920,1440")); doc_name = A.get("doc_name", "VISUAL_ASSEMBLY_GUIDE.md")
    k = {"yaml": md5(yaml_p), "scad": md5(scad)}
    steps = {}
    if A.get("steps_md"):
        sp = os.path.join(P.root, A["steps_md"]); steps = parse_steps(open(sp).read()); k["steps"] = md5(sp)
        steps or (print(f"no '### Step N - title' headings parsed from {A['steps_md']}"), sys.exit(2))
    board = P.path("board"); k["board"] = md5(board) if board and os.path.exists(board) else "MISSING"
    cy = P.path("case_yaml"); k["case"] = str(yaml.safe_load(open(cy)).get("case", {}).get("version", "MISSING")) if cy and os.path.exists(cy) else "MISSING"
    od = os.path.join(P.root, A["out_dir"].replace("{REV}", P.rev()).replace("{MD5_8}", k["board"]).replace("{CASE_VERSION}", k["case"])); gd = os.path.join(od, "guide")
    side_p = os.path.join(gd, "guide.json"); side = json.load(open(side_p)) if os.path.exists(side_p) else {"renders": {}}
    pgs = pages(cfg, steps); stale = []
    orphans = sorted(set(side["renders"]) - {p[0] for p in pgs})
    if orphans and check:
        stale += [f"guide/{s}.png (orphan: no page)" for s in orphans]
    for s_ in orphans if not check else []:
        side["renders"].pop(s_, None); f_ = os.path.join(gd, s_ + ".png"); os.path.exists(f_) and os.remove(f_); print(f"removed orphan guide/{s_}.png")
    for stem, defs, cam, *_ in pgs:
        rk = hashlib.md5(json.dumps([k["scad"], defs, cam, size], sort_keys=True).encode()).hexdigest()[:10]
        f = os.path.join(gd, stem + ".png")
        if side["renders"].get(stem) != rk or not os.path.exists(f):
            if check:
                stale.append(f"guide/{stem}.png"); continue
            os.makedirs(gd, exist_ok=True)
            lower = lambda v: str(v).lower() if isinstance(v, bool) else v
            cmd = A["render_cmd"].format(OUT=shlex.quote(f), CAMERA=shlex.quote(str(cam)), SIZE=shlex.quote(size), DEFS=" ".join(shlex.quote(f"-D{a}={lower(v)}") for a, v in defs.items()))
            r = subprocess.run(cmd, shell=True, cwd=P.root, capture_output=True, text=True)
            if r.returncode or not os.path.exists(f):
                sys.exit(f"assembly_guide: render failed for {stem}: {cmd}\n{(r.stderr or r.stdout)[-600:]}")
            side["renders"][stem] = rk; print(f"rendered guide/{stem}.png")
    md = build_md(cfg, pgs, k, doc_name, size); mp = os.path.join(od, doc_name)
    if check:
        if not os.path.exists(mp) or open(mp).read() != md:
            stale.append(os.path.relpath(mp, P.root))
        if stale:
            print("STALE: " + ", ".join(stale) + " — run scripts/assembly_guide.py"); return 1
        print(f"OK: {os.path.relpath(mp, P.root)} + {len(pgs)} renders up to date"); return 0
    os.makedirs(gd, exist_ok=True); open(mp, "w").write(md)
    side.update({"generator": "scripts/assembly_guide.py", "inputs": k, "size": size}); json.dump(side, open(side_p, "w"), indent=1, sort_keys=True)
    print(f"wrote {os.path.relpath(mp, P.root)} ({len(pgs)} pages) + guide/guide.json"); return 0


def selftest():
    fx = "### Step 2 - Board into the tray (10 s)\n\nESD: wrist strap on. Board onto the bosses, connector toward the rear. It drops in.\n\n![s](x.png)\n\n### Step 7 - Done - end-of-line check\n\nQA every unit. Fine.\n"
    s = parse_steps(fx)
    assert s[2] == ("Board into the tray", 10, "ESD: wrist strap on. Board onto the bosses, connector toward the rear.") and s[7] == ("Done - end-of-line check", None, "QA every unit. Fine."), s
    d = tempfile.mkdtemp(prefix="hwfs_ag_")
    w = lambda p, t: (os.makedirs(os.path.dirname(f"{d}/{p}"), exist_ok=True), open(f"{d}/{p}", "w").write(t))
    w("project.yaml", "project: {name: t}\npaths: {case_yaml: 20-design/case.yaml}\nassembly_guide:\n  yaml: 20-design/assembly_guide.yaml\n  steps_md: out/ASSEMBLY.md\n"
      "  scad: out/case.scad\n  out_dir: 70-release/{REV}\n  doc_name: VISUAL_ASSEMBLY_GUIDE.md\n  size: '640,480'\n"
      "  render_cmd: \"printf 'PNG %s %s %s' {CAMERA} {DEFS} {SIZE} > {OUT}\"\n")
    w("20-design/case.yaml", "case: {version: v0.1-test}\n"); w("out/case.scad", "cube(1);\n"); w("out/ASSEMBLY.md", fx)
    w("20-design/assembly_guide.yaml", "doc: {doc_id: VG-001, title: Illustrated assembly guide, revision: r1, date: 2026-01-01, companions: SOP-001}\nparts: [tray, board]\ntools: [driver]\n"
      "defaults: {defs: {show_text: 'true'}}\npages:\n  - {id: P_pressfit, position: before, heading: 'P — Press-fit', defs: {part: '\"fixture\"'}, camera: '0,0,0,55,0,25,300', lines: [Press once.], parts: [fixture], tools: [press], check: 'flush'}\n"
      "  - {id: X_exploded, position: after, heading: 'X — Exploded view', defs: {part: '\"exploded\"'}, camera: '0,0,0,55,0,25,600'}\n"
      "step_defaults: {camera: '0,0,0,55,0,25,400', defs: {part: '\"step\"'}}\nsteps:\n  2: {camera: '0,0,0,55,0,215,400', parts: [board], tools: [strap], check: 'seated'}\n")
    P = Project(f"{d}/project.yaml")
    assert run(P, check=True) == 1, "check before build must be stale"
    assert run(P) == 0
    od = f"{d}/70-release/rev0"; md = open(f"{od}/VISUAL_ASSEMBLY_GUIDE.md").read()
    assert [p[0] for p in pages(yaml.safe_load(open(f"{d}/20-design/assembly_guide.yaml")), s)] == ["page_P_pressfit", "step_02", "step_07", "page_X_exploded"]
    assert "## Step 2 — Board into the tray (10 s)" in md and "![Step 2" in md and "| board | strap | seated |" in md and "case `v0.1-test`" in md, md
    png = open(f"{od}/guide/step_02.png").read(); assert "0,0,0,55,0,215,400" in png and "-Dstep=2" in png and "-Dpart=\"step\"" in png and "640,480" in png, png
    assert run(P, check=True) == 0, "fresh build must pass --check"
    side = json.load(open(f"{od}/guide/guide.json")); k2 = dict(side["renders"])
    w("20-design/assembly_guide.yaml", open(f"{d}/20-design/assembly_guide.yaml").read().replace("Press once.", "Press once, firmly."))
    assert run(P, check=True) == 1 and run(P) == 0 and json.load(open(f"{od}/guide/guide.json"))["renders"] == k2, "a text edit re-renders nothing"
    w("out/case.scad", "cube(2);\n")
    import io, contextlib
    with contextlib.redirect_stdout(io.StringIO()) as buf:
        assert run(P, check=True) == 1
    assert all(f"guide/{s}.png" in buf.getvalue() for s in ("page_P_pressfit", "step_02", "step_07", "page_X_exploded")), buf.getvalue()   # every render stale
    w("20-design/assembly_guide.yaml", open(f"{d}/20-design/assembly_guide.yaml").read().replace("  - {id: X_exploded", "  # - {id: X_exploded"))
    with contextlib.redirect_stdout(io.StringIO()) as buf:
        assert run(P, check=True) == 1 and "orphan" in buf.getvalue(), buf.getvalue()
    assert run(P) == 0 and not os.path.exists(f"{od}/guide/page_X_exploded.png") and "page_X_exploded" not in json.load(open(f"{od}/guide/guide.json"))["renders"], "orphan render pruned"
    print("selftest OK (step parsing, page order, markdown, {SIZE} quoted, keyed renders: text edit renders nothing, geometry bump stales every page, removed page = orphan pruned)"); return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0]); ap.add_argument("--check", action="store_true"); ap.add_argument("--selftest", action="store_true"); ap.add_argument("--project")
    a = ap.parse_args()
    sys.exit(selftest() if a.selftest else run(Project.find(arg=a.project), check=a.check))
