#!/usr/bin/env python3
"""scripts/collect_renders.py — renderings are release data: collect them under collateral/<board-md5-8>/renders/ with an md5 + grade index.

  python scripts/collect_renders.py [--project project.yaml]
  python scripts/collect_renders.py --check          # (alias --dry) exit 1 when any rule would be redone or a source is missing; writes nothing
  python scripts/collect_renders.py --selftest

project.yaml:
  renders:
    - {name: pcb_top, kind: kicad_render, args: ["--side", "top", "--zoom", "1"]}        # kicad-cli pcb render <args> -o <out> <board>
    - {name: pcb_top_2d, kind: command, cmd: "{KICAD_CLI} pcb export svg --layers F.Cu -o {OUT} {BOARD}"}
    - {name: panel_top, kind: copy, src: "out/fab/*_{MD5_8}/panel/panel_top.png"}     # glob; {MD5_8} = board md5 prefix
    - {name: case_iso, kind: copy, src: "out/case/{CASE_VERSION}/renders/iso.png", key: case}   # case-keyed items use the case version, not the board md5
Freshness key = md5 of the source (or the board) + the FULL argument/command string, so a changed camera re-renders and an unchanged one does
not; the index RENDERS.md / renders.json carries md5, bytes, source key and a grade (OK / EMPTY when the file is < min_bytes). Orphans (files
in the folder that no rule produced) are listed, never deleted. Walk relative paths; a rule may write into a sub-folder.
"""
import argparse, glob, hashlib, json, os, shutil, subprocess, sys, tempfile

import yaml

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from project import Project  # noqa: E402


def file_md5(p):
    return hashlib.md5(open(p, "rb").read()).hexdigest()


def run(P, dry=False, runner=None):
    board = P.path("board")
    label, md5 = P.record_md5()   # the board (ee / both) or the STL set of record (mech scope)
    if md5 is None:
        print(f"MISSING: {label} — renders are keyed on the record md5; nothing collected"); return 1
    case = P.path("case_yaml")
    case_v = ((yaml.safe_load(open(case)) or {}).get("case") or {}).get("version") if case and os.path.exists(case) else None
    out_dir = os.path.join(P.path("collateral_dir"), md5[:8], "renders")
    os.makedirs(out_dir, exist_ok=True)
    idx_path = os.path.join(out_dir, "renders.json")
    idx = json.load(open(idx_path)) if os.path.exists(idx_path) else {}
    sub = lambda s: (s.replace("{MD5_8}", md5[:8]).replace("{CASE_VERSION}", str(case_v)).replace("{BOARD}", board or "")
                     .replace("{KICAD_CLI}", P.tool("kicad_cli") or "kicad-cli").replace("{ROOT}", P.root))
    produced, log = set(), []
    for r in P.get("renders", []) or []:
        name, kind = r["name"], r["kind"]
        if kind == "copy":
            srcs = sorted(glob.glob(os.path.join(P.root, sub(r["src"]))))
            if not srcs:
                log.append(f"MISSING {name}: {sub(r['src'])}"); continue
            src = srcs[-1]
            ext = os.path.splitext(src)[1]
            key = f"copy {file_md5(src)} {r['src']}"
        else:
            ext = r.get("ext", ".png")
            argstr = " ".join(r.get("args", [])) if kind == "kicad_render" else sub(r["cmd"])
            key = f"{kind} {md5} {argstr}"
        out = os.path.join(out_dir, r.get("sub", ""), f"{name}{ext}")
        rel = os.path.relpath(out, out_dir)
        produced.add(rel)
        if idx.get(rel, {}).get("key") == key and os.path.exists(out):
            log.append(f"keep {rel}"); continue
        if dry:
            log.append(f"would redo {rel}"); continue
        os.makedirs(os.path.dirname(out), exist_ok=True)
        if kind == "copy":
            shutil.copy2(src, out)
        elif kind == "kicad_render":
            cmd = [P.tool("kicad_cli") or "kicad-cli", "pcb", "render", *r.get("args", []), "-o", out, board]
            (runner or subprocess.run)(cmd, check=False, capture_output=True)
        elif kind == "command":
            (runner or (lambda c, **k: subprocess.run(c, shell=True, check=False, capture_output=True)))(sub(r["cmd"]).replace("{OUT}", out))
        else:
            log.append(f"unknown kind {kind} for {name}"); continue
        if not os.path.exists(out):
            log.append(f"FAILED {rel}: no output"); continue
        size = os.path.getsize(out)
        idx[rel] = {"key": key, "md5": file_md5(out), "bytes": size, "grade": "OK" if size >= r.get("min_bytes", 64) else "EMPTY"}
        log.append(f"redo {rel} ({idx[rel]['grade']})")
    idx = {k: v for k, v in idx.items() if k in produced}
    orphans = sorted(os.path.relpath(os.path.join(dp, f), out_dir) for dp, _, fs in os.walk(out_dir) for f in fs
                     if os.path.relpath(os.path.join(dp, f), out_dir) not in produced and f not in ("renders.json", "RENDERS.md"))
    if not dry:
        json.dump(idx, open(idx_path, "w"), indent=1, sort_keys=True)
        L = [f"# RENDERS.md — collateral renders for {label} md5 `{md5}`" + (f", case `{case_v}`" if case_v else ""), "",
             "GENERATED by `scripts/collect_renders.py` (idempotent: a file is redone only when its source md5 or its render arguments change). Grade EMPTY = below min_bytes, look at it.", "",
             "| File | md5 | bytes | grade | key |", "|---|---|---|---|---|"]
        L += [f"| `{k}` | `{v['md5'][:8]}` | {v['bytes']} | {v['grade']} | `{v['key'][:60]}` |" for k, v in sorted(idx.items())]
        L += ["", "Orphans (not produced by any rule, not deleted): " + (", ".join(f"`{o}`" for o in orphans) or "none"), ""]
        open(os.path.join(out_dir, "RENDERS.md"), "w").write("\n".join(L))
    print("\n".join(log) or "no renders configured")
    print(f"{out_dir}: {len(idx)} files indexed, orphans {orphans or 'none'}")
    bad = ("FAILED", "MISSING") + (("would redo",) if dry else ())
    return 1 if any(l.startswith(bad) for l in log) else 0


def selftest():
    d = tempfile.mkdtemp(prefix="hwfs_cr_")
    os.makedirs(f"{d}/kicad/b"); os.makedirs(f"{d}/out/fab/2026_dead/panel"); os.makedirs(f"{d}/design")
    open(f"{d}/kicad/b/b.kicad_pcb", "w").write("(kicad_pcb)\n")
    m8 = file_md5(f"{d}/kicad/b/b.kicad_pcb")[:8]
    os.rename(f"{d}/out/fab/2026_dead", f"{d}/out/fab/2026_{m8}")
    open(f"{d}/out/fab/2026_{m8}/panel/panel_top.png", "wb").write(b"x" * 100)
    open(f"{d}/design/case.yaml", "w").write("case: {version: v9}\n")
    os.makedirs(f"{d}/out/case/v9"); open(f"{d}/out/case/v9/iso.png", "wb").write(b"y" * 100)
    open(f"{d}/project.yaml", "w").write(f"""paths: {{board: kicad/b/b.kicad_pcb, case_yaml: design/case.yaml}}
renders:
  - {{name: pcb_top, kind: kicad_render, args: ["--side", "top"]}}
  - {{name: panel_top, kind: copy, src: "out/fab/*_{{MD5_8}}/panel/panel_top.png"}}
  - {{name: case_iso, kind: copy, src: "out/case/{{CASE_VERSION}}/iso.png", sub: case}}
  - {{name: tiny, kind: copy, src: "out/case/{{CASE_VERSION}}/iso.png", min_bytes: 1000}}
""")
    calls = []
    def fake(cmd, **k):
        calls.append(cmd); open(cmd[cmd.index("-o") + 1], "wb").write(b"png" * 40)
    P = Project(f"{d}/project.yaml")
    assert run(P, runner=fake) == 0 and len(calls) == 1
    out = f"{d}/docs/release/collateral/{m8}/renders"
    idx = json.load(open(f"{out}/renders.json"))
    assert set(idx) == {"pcb_top.png", "panel_top.png", "case/case_iso.png", "tiny.png"} and idx["tiny.png"]["grade"] == "EMPTY", idx
    assert run(P, runner=fake) == 0 and len(calls) == 1, "idempotent: nothing redone"
    open(f"{d}/project.yaml", "a").write("")
    P.cfg["renders"][0]["args"] = ["--side", "bottom"]
    assert run(P, dry=True, runner=fake) == 1 and len(calls) == 1, "--check: a rule that would be redone exits 1 and renders nothing"
    assert run(P, runner=fake) == 0 and len(calls) == 2, "a changed camera re-renders"
    assert run(P, dry=True, runner=fake) == 0, "--check green when nothing would be redone"
    open(f"{out}/stale.png", "wb").write(b"z")
    run(P, runner=fake)
    assert "| `case/case_iso.png` |" in open(f"{out}/RENDERS.md").read() and "`stale.png`" in open(f"{out}/RENDERS.md").read().split("Orphans")[1]
    P.cfg["renders"].append({"name": "gone", "kind": "copy", "src": "nowhere/*.png"})
    assert run(P, runner=fake) == 1, "a missing source is reported and exits 1"
    P.cfg["paths"]["board"] = "kicad/none.kicad_pcb"
    assert run(P, runner=fake) == 1 and not os.path.exists(f"{d}/docs/release/collateral/nomd5"), "no board: MISSING, no nomd5 folder"
    print("selftest OK")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--project"); ap.add_argument("--dry", "--check", action="store_true"); ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    sys.exit(selftest() if a.selftest else run(Project.find(arg=a.project), a.dry))
