#!/usr/bin/env python3
"""scripts/known_issues.py — KNOWN_ISSUES.md generated from DECISIONS.md, BLOCKERS.md and the test plan (generated-only rule).

  python scripts/known_issues.py            # rewrite paths.known_issues
  python scripts/known_issues.py --check    # exit 1 (and say so) when the file is stale
  python scripts/known_issues.py --selftest

Sections 2–5 are generated deterministically (no date, so --check is stable). Section 1 is hand-curated: the block between the
markers.hand_curated pair in the existing file is kept verbatim.
Rules: §2 = DECISIONS rows whose status cell starts with OPEN (bold stripped) + rows that mention OPEN elsewhere + rows whose
status says 'provisional'; §2.1 = APPLIED rows whose status cell matches markers.nod_regex (choices applied ahead of the owner's nod);
§3 = every blocker row; §4 = every markers.unverified line of the test plan except the legend that defines the markers.
Guards: every DECISIONS data row has exactly the header's cell count (content pipes escaped as backslash-pipe); no hand-curated §1 row
may cite an agent row whose status starts APPROVED / CONFIRMED / CLOSED / SUPERSEDED unless the row says "resolved" or "by design".
"""
import os, re, sys, tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from project import Project, split_row  # noqa: E402


def rows(path, id_re):
    """[(id, [cells])] for every table row whose first cell carries an ID."""
    out = []
    if not os.path.exists(path):
        return out
    for line in open(path, encoding="utf-8"):
        if line.startswith("|"):
            cells = split_row(line)
            m = id_re.search(cells[0]) if cells else None
            if m:
                out.append((m.group(1), cells))
    return out


def check_tables(path):
    """Every data row carries the header's cell count (generators read cells by position)."""
    width, bad = None, []
    for n, line in enumerate(open(path, encoding="utf-8"), 1):
        if line.startswith("|"):
            k = len(split_row(line))
            width = width or k
            if k != width:
                bad.append(f"{os.path.basename(path)}:{n} has {k} cells, header has {width}")
    return bad


def check_section1(section1, st, agent_re):
    closed = ("APPROVED", "CONFIRMED", "CLOSED", "SUPERSEDED")
    bad = []
    for line in section1.splitlines():
        if not line.startswith("| ") or line.startswith("| Symptom") or "resolved" in line.lower() or "by design" in line.lower():
            continue
        for cc in set(agent_re.findall(split_row(line)[-1])):
            if st.get(cc, "").startswith(closed):
                bad.append(f"KNOWN_ISSUES §1 cites {cc} ({st[cc][:40]}…) without 'resolved'/'by design': {line[:70]}…")
    return bad


def cut(s, n):
    s = re.sub(r"<br\s*/?>", " ", s).replace("|", "/")
    return s if len(s) <= n else s[: n - 1] + "…"


def status(cell):
    return re.sub(r"\*\*", "", cell).strip()


def build(P, section1):
    id_re, agent_re = P.id_re(), re.compile(r"\b%s-\d{3}\b" % re.escape(P.get("ids.agent_prefix")))
    dec = rows(P.path("decisions"), id_re)
    st = {i: status(c[2]) for i, c in dec if len(c) > 2}
    bad = check_tables(P.path("decisions")) + check_section1(section1, st, agent_re)
    if bad:
        sys.exit("\n".join(bad))
    live = lambda i: st[i].split("(was:")[0]  # the "(was: …)" history does not count
    opened = [(i, c) for i, c in dec if st[i].startswith("OPEN")]
    partial = [i for i, c in dec if not st[i].startswith(("OPEN", "CLOSED")) and re.search(r"\bOPEN\b", st[i])]
    provisional = [(i, c) for i, c in dec if not st[i].startswith("OPEN") and "provisional" in live(i).lower()]
    nods = [(i, c) for i, c in dec if not st[i].startswith(("OPEN", "CLOSED", "SUPERSEDED", "REJECTED")) and re.search(P.get("markers.nod_regex"), live(i), re.I)]
    name, ki = P.get("project.name", "project"), os.path.relpath(P.path("known_issues"), P.root)
    L = [f"# {os.path.basename(ki)} — every OPEN / BLOCKED / UNVERIFIED item of {name}, with its ID", "",
         f"GENERATED by `scripts/known_issues.py` from `{P.get('paths.decisions')}` (rows whose status cell **starts with** OPEN; rows that mention OPEN elsewhere "
         f"and provisional rows listed separately), `{P.get('paths.blockers')}` (all rows) and the {' / '.join(P.get('markers.unverified'))} markers of `{P.get('paths.test_plan')}`. "
         "Sections 2–5 are rewritten on every run — do not edit them by hand; section 1 (between the hand-curated markers) is kept and must be "
         "updated by hand when a row closes. `--check` exits 1 when this file is stale.", "",
         section1.rstrip(), "",
         "## 2. OPEN decision rows", "", "| ID | Status (as written) | Subject |", "|---|---|---|"]
    L += [f"| {i} | {cut(st[i], 110)} | {cut(c[3], 140)} |" for i, c in opened]
    L += ["", "Mentions OPEN in a non-OPEN status cell: " + (", ".join(f"**{i}** ({cut(st[i], 90)})" for i in partial) or "none") + ".", "",
          "DECIDED **provisional** (applied, flagged to the owner): " + (", ".join(f"**{i}** — {cut(c[3], 110)}" for i, c in provisional) or "none") + ".", "",
          "### 2.1 APPLIED, owner nod outstanding (status cell carries the nod marker — rule 2: applied without approval; the order checklist refuses while any is pending)", "",
          "| ID | Status (as written) | Subject |", "|---|---|---|",
          *[f"| {i} | {cut(st[i], 160)} | {cut(c[3], 120)} |" for i, c in nods], *(["| — | none | |"] if not nods else []), "",
          "## 3. BLOCKED", "", "| ID | Item | Result | Impact / workaround |", "|---|---|---|---|"]
    L += [f"| {i} | {cut(c[2], 120)} | {cut(c[4], 120)} | {cut(c[5], 160)} |" for i, c in rows(P.path("blockers"), id_re) if len(c) >= 6]
    L += ["", "## 4. UNVERIFIED markers in the test plan", "", "| Line | Marker | Context |", "|---|---|---|"]
    tp, marks = P.path("test_plan"), "|".join(map(re.escape, P.get("markers.unverified")))
    if tp and os.path.exists(tp):
        for n, line in enumerate(open(tp, encoding="utf-8"), 1):
            m = re.search(marks, line)
            if m and not re.search(r"\*\*(%s)\*\* =" % marks, line):
                L.append(f"| {n} | {m.group(0)} | {cut(line.strip(), 150)} |")
    L += ["", "## 5. Regenerate", "", "`scripts/known_issues.py` after every DECISIONS / BLOCKERS / test-plan change (`--check` only compares). "
          "Section 1 is the hand-curated index: edit it between the markers when a row closes or a new symptom is understood.", ""]
    return "\n".join(L)


def run(P, check):
    out = P.path("known_issues")
    begin, end = P.get("markers.hand_curated")
    text = open(out, encoding="utf-8").read() if os.path.exists(out) else ""
    if begin not in text or end not in text:
        sys.exit(f"{out}: hand-curated block ({begin} … {end}) missing — add the markers around section 1 first")
    new = build(P, text[text.index(begin): text.index(end) + len(end)])
    if check:
        if new != text:
            print(f"STALE: {out} differs from scripts/known_issues.py output — run scripts/known_issues.py")
            return 1
        print(f"OK: {out} up to date")
        return 0
    open(out, "w", encoding="utf-8").write(new)
    print(f"{out} written")
    return 0


def selftest():
    d = tempfile.mkdtemp(prefix="hwfs_ki_")
    os.makedirs(f"{d}/docs")
    open(f"{d}/project.yaml", "w").write("project: {name: t}\n")
    open(f"{d}/docs/DECISIONS.md", "w").write("| ID | Date | Status | Topic | Proposal | Reason |\n|---|---|---|---|---|---|\n"
        "| **D-01 (owner)** | 2026-01-01 | **APPROVED** | a | b | c |\n| CC-001 | 2026-01-01 | OPEN (owner question) | q | p | r |\n"
        "| CC-002 | 2026-01-01 | APPLIED (!) owner look wanted | nod | p | r |\n| CC-003 | 2026-01-01 | DECIDED (provisional) | prov | p \\| pipe | r |\n")
    open(f"{d}/docs/BLOCKERS.md", "w").write("| ID | Date | Item | Tried | Result | Impact |\n|---|---|---|---|---|---|\n| B-01 | 2026-01-01 | ds | curl | 403 | guess not |\n")
    open(f"{d}/docs/TEST_PLAN.md", "w").write("legend: **UNVERIFIED** = not measured\nT1 UNVERIFIED value\n")
    open(f"{d}/docs/KNOWN_ISSUES.md", "w").write("<!-- hand-curated: begin -->\n## 1. x\n| Symptom | Cause | ID |\n|---|---|---|\n| s | c | CC-001 |\n<!-- hand-curated: end -->\n")
    P = Project(f"{d}/project.yaml")
    assert run(P, False) == 0 and run(P, True) == 0
    t = open(f"{d}/docs/KNOWN_ISSUES.md").read()
    assert "| CC-001 | OPEN (owner question) |" in t and "| CC-002 | APPLIED (!)" in t and "**CC-003**" in t and "| B-01 |" in t and "| 2 | UNVERIFIED |" in t
    assert "| 1 | UNVERIFIED |" not in t, "legend line must be skipped"
    open(f"{d}/docs/DECISIONS.md", "a").write("| CC-004 | 2026-01-01 | OPEN | new | p | r |\n")
    assert run(P, True) == 1, "must be STALE after a new row"
    open(f"{d}/docs/DECISIONS.md", "a").write("| CC-005 | bad row |\n")
    try:
        run(P, True); raise AssertionError("cell-count guard missing")
    except SystemExit as e:
        assert "cells" in str(e)
    print("selftest OK")


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        selftest()
    else:
        sys.exit(run(Project.find(), "--check" in sys.argv))
