#!/usr/bin/env python3
"""scripts/now_pages.py — the five pages of `00-now/`, each the answer to its own file name, derived from the logs and the kits only:
  WHERE_THINGS_STAND.md   gates (approved / open), the last three landed log entries, the revision + record identity, open blockers
  BLOCKED_ON_OWNER.md     OPEN decision rows that name the owner, arrival-checklist rows the owner closes, kit fit results still pending
  WHAT_TO_PRINT.md        one row per plate sidecar under <kits_dir>/<kit>/plates/ (time, grams, changes, what it proves, case version), in print
                          order; a row is BROKEN when its .3mf or the kit's START_HERE.md is missing, a required key is absent, or an stl_md5s
                          entry is not a part of the kit
  WHAT_TO_ORDER.md        procurement rows whose "Order qty" is filled but no order is recorded, fab orders in flight (the quotes index)
  WHAT_TO_CHECK_ON_ARRIVAL.md   arrival-checklist rows not DONE / N/A / APPLIED
  scripts/now_pages.py            write the five pages into paths.now_dir (00-now)
  scripts/now_pages.py --check    exit 1 when any page differs from a regenerate (the Generated line excluded) — gates.adopt
  scripts/now_pages.py --selftest
Never hand-edited: the pages are rebuilt by the record round and a stale page fails the gates like a stale release report. Sources are the
paths the layout names (scripts/project.py DEFAULTS); nothing here reads a README. Sidecar keys read (references/print-kit.md §4): print_time_s,
filament_g, objects, optional filament_changes, proves, order, stl_md5s, case_version."""
import glob, hashlib, json, os, re, sys, time

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
from project import Project  # noqa: E402

VOLATILE = re.compile(r"^Generated .*$", re.M)
PAGES = ["WHERE_THINGS_STAND.md", "BLOCKED_ON_OWNER.md", "WHAT_TO_PRINT.md", "WHAT_TO_ORDER.md", "WHAT_TO_CHECK_ON_ARRIVAL.md"]
CLOSED = ("DONE", "N/A", "APPLIED", "CLOSED")


def rel(P, key):
    return P.get(f"paths.{key}") or ""


def table(path):
    """markdown table rows of a file -> (header cells, [row cells]); the first table only; rule rows skipped"""
    if not path or not os.path.exists(path):
        return [], []
    hdr, out = [], []
    for l in open(path, encoding="utf-8"):
        if not l.startswith("|"):
            if hdr and out:
                break
            continue
        if re.match(r"^\|\s*:?-", l):
            continue
        cells = [c.strip() for c in l.strip().strip("|").split("|")]
        if not hdr:
            hdr = cells
        else:
            out.append(cells)
    return hdr, out


def head(title):
    return [f"# {title}", "", "GENERATED by `scripts/now_pages.py` from the records — do not edit; regenerate (a stale page fails the gates).",
            "Generated " + time.strftime("%Y-%m-%d %H:%M"), ""]


def arrival_rows(P):
    y = P.get("arrival_checklist.yaml")
    if not y or not os.path.exists(y):
        return []
    import yaml
    d = yaml.safe_load(open(y, encoding="utf-8")) or {}
    out = []
    for s in d.get("sections") or []:
        for r in s.get("rows") or []:
            if isinstance(r, dict) and "id" in r:
                out.append(dict(r, section=s.get("key", "")))
    return out


def status_entries(P):
    """dated log entries of STATUS (`**YYYY-MM-DD …**` paragraphs or `- YYYY-MM-DD …` bullets), in file order"""
    p = P.path("status")
    if not p or not os.path.exists(p):
        return []
    return [l.rstrip() for l in open(p, encoding="utf-8") if re.match(r"^(\*\*|- \*\*|- )\d{4}-\d\d-\d\d", l)]


def where(P):
    L = head("Where things stand")
    lab, md5 = P.record_md5()
    L += [f"- Revision **{P.rev()}** — {lab} md5 `{(md5 or 'MISSING')[:8]}`", ""]
    _, g = table(P.path("gates"))
    gates = [r for r in g if len(r) >= 4 and r[0]]
    L += ["## Gates", ""]
    L += [f"- {r[0].strip('* ')}: " + ("open" if not r[3] or "not yet" in r[3].lower() or r[3].startswith("_") else f"approved — {r[3]}") for r in gates] or ["- nothing"]
    L += ["", "## Landed (newest first)", ""]
    st = status_entries(P)
    L += [("- " + e.lstrip("- ")) for e in reversed(st[-3:])] or ["- nothing"]
    L += ["", "## Blockers", ""]
    _, b = table(P.path("blockers"))
    L += [f"- {r[0]}: {r[2] if len(r) > 2 else ''}" for r in b if r and r[0]] or ["- nothing"]
    return "\n".join(L) + "\n"


def blocked(P):
    L = head("Blocked on the owner")
    _, d = table(P.path("decisions"))
    dec = [r for r in d if len(r) > 3 and "OPEN" in r[2].upper() and "owner" in r[2].lower()]
    L += ["## Decisions waiting for the owner", ""]
    L += [f"- {r[0].strip('* ')}: {r[3]} — answer in `{rel(P, 'decisions')}`" for r in dec] or ["- nothing"]
    own = [r for r in arrival_rows(P) if not str(r.get("status", "")).upper().startswith(CLOSED) and "owner" in (str(r.get("item", "")) + str(r.get("opens", ""))).lower()]
    L += ["", "## Arrival rows the owner closes", ""]
    L += [f"- {r['id']}: {r.get('item', '')}" for r in own] or ["- nothing"]
    fit = P.get("kickoff.enclosure.fit_result")
    L += ["", "## Fit results still pending", ""]
    L += [f"- `kickoff.enclosure.fit_result`: {fit}"] if isinstance(fit, str) and fit.lower().startswith("pending") else ["- nothing"]
    return "\n".join(L) + "\n"


def to_print(P):
    L = head("What to print")
    kd = rel(P, "kits_dir")
    if P.get("project.scope") == "ee":
        return "\n".join(L + ["- nothing to print in this scope"]) + "\n"
    plates = sorted(glob.glob(os.path.join(P.root, kd, "*", "plates", "*.3mf.json")))
    if not plates:
        return "\n".join(L + [f"- nothing: no plate sidecar under `{kd}/<kit>/plates/`"]) + "\n"
    L += ["Print order: the coupon, then ONE part, then the plate (the kit's START_HERE says how). Rows come from the plate sidecars; a BROKEN row "
          "is a plate the kit cannot vouch for (no .3mf, no START_HERE, a key missing, an STL md5 that is not a part of the kit).", "",
          "| kit | plate | time | filament | changes | proves | case | start here | status |", "|---|---|---|---|---|---|---|---|---|"]
    items = []; broken = 0
    for p in plates:
        s = json.load(open(p, encoding="utf-8"))
        kit = os.path.basename(os.path.dirname(os.path.dirname(p))); plate = os.path.basename(p)[: -len(".3mf.json")]
        items.append((int(s.get("order", 99)), kit, plate, s, plate_problems(os.path.join(P.root, kd, kit), p, s)))
    for _, kit, plate, s, why in sorted(items, key=lambda x: (x[0], x[1], x[2])):
        broken += bool(why)
        L.append(f"| {kit} | {plate} | {int(s.get('print_time_s', 0)) // 60} min | {s.get('filament_g', 0)} g | {int(s.get('filament_changes', 0))} changes | {s.get('proves', '')} | "
                 f"{s.get('case_version', '-')} | `{kd}/{kit}/START_HERE.md` | {'BROKEN: ' + '; '.join(why) if why else 'ok'} |")
    if broken:
        L += ["", f"- {broken} broken plate(s)"]
    return "\n".join(L) + "\n"


def plate_problems(kit_dir, sidecar, s):
    """Why a plate row is BROKEN (references/print-kit.md §4): the .3mf beside the sidecar, START_HERE.md at the kit root, the two required
    keys, and every `stl_md5s` entry among the md5s of <kit>/parts/*.stl. [] = sound."""
    why = []
    if not os.path.exists(sidecar[: -len(".json")]):
        why.append("no .3mf")
    if not os.path.exists(os.path.join(kit_dir, "START_HERE.md")):
        why.append("no START_HERE.md")
    why += [f"missing {k}" for k in ("print_time_s", "filament_g") if k not in s]
    if s.get("stl_md5s"):
        have = {hashlib.md5(open(f, "rb").read()).hexdigest() for f in glob.glob(os.path.join(kit_dir, "parts", "*.stl"))}
        why += [f"stl md5 {str(m)[:8]} not in parts/" for m in s["stl_md5s"] if m not in have]
    return why


def to_order(P):
    L = head("What to order")
    hdr, pr = table(P.path("procurement"))
    low = [h.lower() for h in hdr]
    qi = next((i for i, h in enumerate(low) if h.startswith("order qty")), None)
    oi = next((i for i, h in enumerate(low) if h in ("ordered", "order", "order placed", "po")), None)
    todo = []
    for r in pr:
        qty = r[qi] if qi is not None and len(r) > qi else ""
        placed = r[oi] if oi is not None and len(r) > oi else ""
        if qty and not placed:
            todo.append(r)
    L += ["## Not yet ordered (procurement rows with an order quantity and no order recorded)", ""]
    L += [f"- {r[0]} {r[1] if len(r) > 1 else ''}: {r[2] if len(r) > 2 else ''} × {r[qi] if qi is not None and len(r) > qi else '?'}" for r in todo] or ["- nothing"]
    L += ["", "## Fab orders in flight", ""]
    idx = glob.glob(os.path.join(P.root, rel(P, "orders_dir"), "ORDER_*.md"))
    L += [f"- `{os.path.relpath(f, P.root)}`" for f in sorted(idx)] or ["- nothing"]
    return "\n".join(L) + "\n"


def to_check(P):
    L = head("What to check on arrival")
    ac = [r for r in arrival_rows(P) if not str(r.get("status", "")).upper().startswith(CLOSED)]
    L += [f"- {r['id']}: {r.get('item', '')} — {r.get('how', '')}" for r in ac] or ["- nothing"]
    return "\n".join(L) + "\n"


def render(P):
    return dict(zip(PAGES, [where(P), blocked(P), to_print(P), to_order(P), to_check(P)]))


def main(argv):
    if "--selftest" in argv:
        return selftest()
    P = Project.find(); os.chdir(P.root); out = rel(P, "now_dir") or "00-now"; pages = render(P)
    if "--check" in argv:
        bad = [n for n, t in pages.items() if not os.path.exists(f"{out}/{n}") or VOLATILE.sub("", open(f"{out}/{n}", encoding="utf-8").read()) != VOLATILE.sub("", t)]
        for n in bad:
            print(f"STALE: {out}/{n} differs from scripts/now_pages.py output — run scripts/now_pages.py")
        if bad:
            return 1
        print(f"OK: {out}/ up to date ({len(pages)} pages)"); return 0
    os.makedirs(out, exist_ok=True)
    for n, t in pages.items():
        open(f"{out}/{n}", "w", encoding="utf-8").write(t)
    print(f"{out}/ written ({len(pages)} pages)"); return 0


def selftest():
    import tempfile
    d = tempfile.mkdtemp(prefix="hwfs_now_"); os.chdir(d)
    w = lambda p, t: (os.makedirs(os.path.dirname(p) or ".", exist_ok=True), open(p, "w", encoding="utf-8").write(t))
    w("project.yaml", "project: {name: t, scope: both, revision: rev0}\narrival_checklist: {yaml: 20-design/arrival_checklist.yaml}\nkickoff: {enclosure: {fit_result: 'pending: bracket print'}}\n")
    w("90-log/GATES.md", "# G\n| Gate | Meaning | Prerequisites | Owner approval |\n|---|---|---|---|\n| **G0** | spec | x | owner, 2026-01-01, SPEC r1 |\n| **G1** | sch | y | _not yet approved_ |\n")
    w("90-log/DECISIONS.md", "| ID | Date | Status | Topic | Proposal | Reason |\n|---|---|---|---|---|---|\n| **D-07** | d | **OPEN** (owner) | widen root | yes or no | r |\n| CC-010 | d | APPLIED | x | p | r |\n")
    w("90-log/STATUS.md", "# S\n## Log\n**2026-01-01 09:00 — created.**\n**2026-01-02 09:00 — schematic drawn.**\n**2026-01-03 09:00 — layout started.**\n**2026-01-04 09:00 — layout routed.**\n")
    w("90-log/BLOCKERS.md", "| ID | Date | Item | What was tried | Result | Impact |\n|---|---|---|---|---|---|\n| B-01 | d | datasheet page 4 missing | mail | open | none |\n")
    w("20-design/arrival_checklist.yaml", "sections:\n  - key: B\n    rows:\n      - {id: B-1, item: 'switch sense', how: 'continuity', status: TODO}\n      - {id: B-2, item: 'polarity', how: 'Vf', status: 'DONE 2026-01-05'}\n      - {id: E-1, item: 'the owner decides the fit knob', how: 'print', status: TODO, opens: owner}\n")
    w("60-orders/PROCUREMENT.md", "| Line | Class | MPN | Order qty | Ordered |\n|---|---|---|---|---|\n| 1 | screw | M3x8 | 100 | |\n| 2 | insert | HS-M3 | 50 | 2026-01-02 |\n")
    w("60-orders/ORDER_rev0.md", "# order\n")
    import hashlib
    w("50-kits/home_fdm/START_HERE.md", "# start\n"); w("50-kits/home_fdm/parts/a.stl", "solid a\nendsolid a\n"); amd5 = hashlib.md5(b"solid a\nendsolid a\n").hexdigest()
    w("50-kits/home_fdm/plates/body.3mf", ""); w("50-kits/home_fdm/plates/body.3mf.json", json.dumps({"print_time_s": 3600, "filament_g": 12.5, "objects": ["a"], "filament_changes": 2, "proves": "fit", "order": 2, "stl_md5s": [amd5], "case_version": "v3"}))
    w("50-kits/home_fdm/plates/coupon.3mf", ""); w("50-kits/home_fdm/plates/coupon.3mf.json", json.dumps({"print_time_s": 600, "filament_g": 1.5, "objects": ["c"], "proves": "legend", "order": 1}))
    # BROKEN plates: no .3mf beside the sidecar, a missing key, an md5 that is not a part of the kit, a kit without START_HERE
    w("50-kits/home_fdm/plates/no3mf.3mf.json", json.dumps({"print_time_s": 1, "filament_g": 1, "objects": [], "order": 9}))
    w("50-kits/home_fdm/plates/nokey.3mf", ""); w("50-kits/home_fdm/plates/nokey.3mf.json", json.dumps({"print_time_s": 1, "objects": [], "order": 9}))
    w("50-kits/home_fdm/plates/badmd5.3mf", ""); w("50-kits/home_fdm/plates/badmd5.3mf.json", json.dumps({"print_time_s": 1, "filament_g": 1, "objects": [], "order": 9, "stl_md5s": [amd5, "0" * 32]}))
    w("50-kits/nostart/plates/x.3mf", ""); w("50-kits/nostart/plates/x.3mf.json", json.dumps({"print_time_s": 1, "filament_g": 1, "objects": [], "order": 9}))
    P = Project.find(start=d); pages = render(P)
    assert set(pages) == set(PAGES)
    wt = pages["WHERE_THINGS_STAND.md"]
    assert "G0: approved — owner, 2026-01-01, SPEC r1" in wt and "G1: open" in wt and "B-01: datasheet page 4 missing" in wt, wt
    assert wt.index("2026-01-04") < wt.index("2026-01-03") < wt.index("2026-01-02") and "2026-01-01 09:00" not in wt, "last three entries, newest first"
    assert len(wt.splitlines()) < 60
    bl = pages["BLOCKED_ON_OWNER.md"]
    assert "D-07: widen root" in bl and "CC-010" not in bl and "E-1: the owner decides" in bl and "B-1" not in bl and "pending: bracket print" in bl, bl
    tp = pages["WHAT_TO_PRINT.md"]
    assert "| home_fdm | coupon | 10 min | 1.5 g | 0 changes | legend | - | `50-kits/home_fdm/START_HERE.md` | ok |" in tp and tp.index("coupon") < tp.index("| body |"), tp
    assert "| home_fdm | body | 60 min | 12.5 g | 2 changes | fit | v3 | `50-kits/home_fdm/START_HERE.md` | ok |" in tp, tp
    for row, why in (("no3mf", "BROKEN: no .3mf |"), ("nokey", "BROKEN: missing filament_g |"), ("badmd5", "BROKEN: stl md5 00000000 not in parts/ |"), ("| nostart | x |", "BROKEN: no START_HERE.md |")):
        line = next(l for l in tp.splitlines() if row in l); assert line.endswith(why), (row, line)
    assert "- 4 broken plate(s)" in tp and "objects_in_3mf" not in open(__file__).read().split("def selftest")[0], tp
    to = pages["WHAT_TO_ORDER.md"]
    assert "1 screw: M3x8 × 100" in to and "HS-M3" not in to and "ORDER_rev0.md" in to, to
    tc = pages["WHAT_TO_CHECK_ON_ARRIVAL.md"]
    assert "B-1: switch sense — continuity" in tc and "B-2" not in tc, tc
    # write + check, then a hand edit is STALE
    assert main([]) == 0 and main(["--check"]) == 0
    open("00-now/BLOCKED_ON_OWNER.md", "a").write("- hand edit\n"); assert main(["--check"]) == 1
    # ee scope: nothing to print in this scope; an empty project: every page says nothing
    w("project.yaml", "project: {name: t, scope: ee}\n"); P = Project.find(start=d)
    assert "nothing to print in this scope" in to_print(P)
    e = tempfile.mkdtemp(prefix="hwfs_now_empty_"); os.chdir(e); w("project.yaml", "project: {name: e, scope: mech}\n")
    w("90-log/GATES.md", "| Gate | Meaning | Prerequisites | Owner approval |\n|---|---|---|---|\n")
    P = Project.find(start=e); pages = render(P)
    assert all("nothing" in t for t in pages.values()), [n for n, t in pages.items() if "nothing" not in t]
    assert main([]) == 0 and sorted(os.listdir("00-now")) == sorted(PAGES)
    print("selftest OK (five pages from gates / decisions / status / blockers / arrival yaml / procurement / kit sidecars; newest-first log; "
          "print order; --check catches a hand edit; ee scope prints nothing; an empty project says nothing on every page)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
